services:
  postgres:
    image: postgres:16
    container_name: pg-db
    environment:
      POSTGRES_DB: psqldb
      POSTGRES_USER: psqlid
      POSTGRES_PASSWORD: psqlpw
    ports:
      - "5432:5432"
    volumes:
      - mes_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg_id -d pg_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mes_db_data: